export const LOAD_CLIENTS_SUCCESS = "LOAD_CLIENTS_SUCCESS";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const DELETE_CLIENT_OPTIMISTIC = "DELETE_CLIENT_OPTIMISTIC";

export const API_CALL_ERROR = "API_CALL_ERROR";
export const BEGIN_API_CALL = "BEGIN_API_CALL";

export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const DELETE_PROJECT_OPTIMISTIC = "DELETE_PROJECT_OPTIMISTIC";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER_OPTIMISTIC = "DELETE_USER_OPTIMISTIC";

export const LOAD_EMPLOYEES_SUCCESS = "LOAD_EMPLOYEES_SUCCESS";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_OPTIMISTIC = "DELETE_EMPLOYEE_OPTIMISTIC";

export const LOAD_ASSIGNMENTS_SUCCESS = "LOAD_ASSIGNMENTS_SUCCESS";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";
export const UPDATE_ASSIGNMENT_SUCCESS = "UPDATE_ASSIGNMENT_SUCCESS";
export const DELETE_ASSIGNMENT_OPTIMISTIC = "DELETE_ASSIGNMENT_OPTIMISTIC";

export const LOAD_CANDIDATES_SUCCESS = "LOAD_CANDIDATES_SUCCESS";
export const CREATE_CANDIDATE_SUCCESS = "CREATE_CANDIDATE_SUCCESS";
export const UPDATE_CANDIDATE_SUCCESS = "UPDATE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_OPTIMISTIC = "DELETE_CANDIDATE_OPTIMISTIC";

export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const DELETE_COMMENT_OPTIMISTIC = "DELETE_COMMENT_OPTIMISTIC";

export const LOAD_NOTIFICATIONS_SUCCESS = "LOAD_NOTIFICATIONS_SUCCESS";
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_OPTIMISTIC = "DELETE_NOTIFICATION_OPTIMISTIC";
